### PR TITLE
FIX: added new endpoint and handler for sql

### PR DESCRIPTION
**Pull request by jakcpto**
Added new endpoint to request drillthrough for kpi sql and handler method for sql.
Corresponding issue https://github.com/intersystems-community/DeepSeeWeb/issues/291

### CODE REVIEW

**Comment by eduard93** [comment]
The scope for sql injection is too large. Please rewrite to accept kpi name instead so that sql is calculated on a server.

**Comment by jakcpto** [comment]
@eduard93 I think for now we can use this solution similar to 
`ClassMethod WriteJSONfromMDX(MDX As %String, Timeout As %Integer = 0) As %Status`
This MDX method is also can be injected.

But the main reason is how frontend works with filters.
It simply add string at the end with filters.
In SQL and MDX requests both.

And for now it cannot use filters another way.

**Comment by evshvarov** [comment]
I agree with @jakcpto . @eduard93 , WriteJSONfromMDX same inject unsafe. I suggest we implement now in "unsafe" mode, and add an issue to fix both MDX, MDXDrillthrough and SQLDrillthrough in the future.

**Comment by eduard93** [comment]
No. MDX is "SELECT" only, limited to cubes. Plus access is still controlled by DeepSee engine/cube security. SQL offers a much larger attack vector. You can pass like this:
```json
{
    "kpi": "kpi_name",
    "filters": [
        { "column": "abc", "operator": "EQUALS", "value": "Bob"},
        ...
    ]
}
```

Filters must be checked for being a valid column present in the kpi query and not a `; DROP TABLE ...`. Values must be passed as parameters.

Check [RESTForms example](https://github.com/intersystems-community/RESTForms2/blob/master/src/Form/JSON/SQL.cls).

**Comment by jakcpto** [comment]
Also added 
FIX: display format data for meters in case of KPI source

**Pull request closed without merging**
