### PR TITLE
Change WriteDrillthroughJSON method

### PR DESCRIPTION
**Pull request by Njektt**

### CODE REVIEW

**Comment by jakcpto** [comment]
This pull request fixing issue discovered in DSW https://github.com/intersystems-community/DeepSeeWeb/issues/264

**Comment by jakcpto** [comment]
@eduard93 here is debug output:

IRISAPP>d ##class(MDX2JSON.Utils).WriteDrillthroughJSON("DRILLTHROUGH SELECT FROM [HOLEFOODS] %FILTER ([DateOfSale].[Actual].[YearSold].&[2017]) %LISTING [ListingX]")

MDX: **DRILLTHROUGH SELECT FROM [HOLEFOODS] %FILTER ([DateOfSale].[Actual].[YearSold].&[2017]) %LISTING** [ListingX]

SQL: **SELECT ID,UnitsSold,Outlet->City FROM HoleFoods.SalesTransaction source WHERE  source.%ID IN (SELECT _DSsourceId FROM HoleFoods_Cube.Listing WHERE _DSqueryKey = 'en767687656')**

**Comment by eduard93** [comment]
Could you try to construct a schemaless example please, or share the class?

i,e, `SELECT '0.5', '.6'`

**Comment by jakcpto** [comment]
@eduard93 you can try to run container from https://github.com/evshvarov/Samples-BI
and open http://localhost:52773/dsw/index.html#/IRISAPP/Two%20Subject%20Areas%20Together.dashboard

**Comment by eduard93** [comment]
Case:
```
s SQL="SELECT '5125.72','1714.50'"
do ##class(%ZEN.Auxiliary.jsonSQLProvider).%WriteJSONFromSQL(,SQL)
{
"children":[
{"HostVar_1":5125.72,"HostVar_2":"1714.50"}
]
}
```

**Comment by eduard93** [comment]
Fixed [here](https://github.com/intersystems-ru/Cache-MDX2JSON/commit/78f29b7183277d6a3f18dd070e578d4d582fb5ac)

**Comment by jakcpto** [comment]
Yes, looks like fixed ) Thanks.

**Pull request closed without merging**
